### ISSUE TITLE
ActionView::Template::Error

### ISSUE THREAD

**Issue by tomposmiko** [peclik/clipboard_image_paste#50]
After installing on redmine 2.5.2, I get the following error:

```
Started GET "/login?back_url=https%3A%2F%2Fredmine-test.eutecus.com%2F" for 80.98.254.83 at 2015-10-11 11:44:04 -0700
Processing by AccountController#login as HTML
  Parameters: {"back_url"=>"https://redmine-test.eutecus.com/"}
  Current user: anonymous
  Rendered account/login.html.erb within layouts/base (1.5ms)
Missing template, responding with 404
  Rendered common/error.html.erb within layouts/base (0.0ms)
Completed 500 Internal Server Error in 10.5ms

ActionView::Template::Error (Missing partial clipboard_image_paste/headers with {:locale=>[:en], :formats=>[:html], :handlers=>[:erb, :builder, :rsb]}. Searched in:
  * "/usr/share/redmine/app/views"
):
    11: <%= stylesheet_link_tag 'rtl', :media => 'all' if l(:direction) == 'rtl' %>
    12: <%= javascript_heads %>
    13: <%= heads_for_theme %>
    14: <%= call_hook :view_layouts_base_html_head %>
    15: <!-- page specific tags -->
    16: <%= yield :header_tags -%>
    17: </head>
  lib/redmine/hook.rb:111:in `block in render_on'
  lib/redmine/hook.rb:61:in `block (2 levels) in call_hook'
  lib/redmine/hook.rb:61:in `each'
  lib/redmine/hook.rb:61:in `block in call_hook'
  lib/redmine/hook.rb:58:in `tap'
  lib/redmine/hook.rb:58:in `call_hook'
  lib/redmine/hook.rb:158:in `call_hook'
  app/views/layouts/base.html.erb:14:in `_app_views_layouts_base_html_erb___3984061904807760966_44002140'
  app/controllers/application_controller.rb:452:in `block (2 levels) in render_error'
  app/controllers/application_controller.rb:450:in `render_error'
  app/controllers/application_controller.rb:438:in `render_404'
  app/controllers/application_controller.rb:462:in `missing_template'
```

**Comment by homebeaver** [comment]
same problem with 3.3.0, so I uninstall the _clipboard_image_paste-1.9_ :

```
Environment:
  Redmine version                3.3.0.stable
  Ruby version                   2.3.1-p112 (2016-04-26) [x86_64-linux-gnu]
  Rails version                  4.2.6
  Environment                    production
  Database adapter               Mysql2
SCM:
  Git                            2.7.4
  Filesystem                     
Redmine plugins:
  redmine_knowledgebase          3.2.1
  scrum                          0.14.0
```
log:

```
ActionView::Template::Error (Missing partial clipboard_image_paste/_headers with {:locale=>[:de, :en], :formats=>[:html], :variants=>[], :handlers=>[:erb, :builder, :raw, :ruby, :rsb]}. Searched in:
  * "/usr/share/redmine-3.3.0/plugins/scrum/app/views" 
  * "/usr/share/redmine-3.3.0/plugins/redmine_knowledgebase/app/views" 
  * "/usr/share/redmine-3.3.0/app/views" 
):
    13: <%= stylesheet_link_tag 'rtl', :media => 'all' if l(:direction) == 'rtl' %>
    14: <%= javascript_heads %>
    15: <%= heads_for_theme %>
    16: <%= call_hook :view_layouts_base_html_head %>
    17: <!-- page specific tags -->
    18: <%= yield :header_tags -%>
    19: </head>
  lib/redmine/hook/view_listener.rb:59:in `block (2 levels) in render_on'
  lib/redmine/hook/view_listener.rb:57:in `map'
  lib/redmine/hook/view_listener.rb:57:in `block in render_on'
  lib/redmine/hook.rb:61:in `block (2 levels) in call_hook'
  lib/redmine/hook.rb:61:in `each'
  lib/redmine/hook.rb:61:in `block in call_hook'
  lib/redmine/hook.rb:58:in `tap'
  lib/redmine/hook.rb:58:in `call_hook'
  lib/redmine/hook.rb:96:in `call_hook'
  app/views/layouts/base.html.erb:16:in `_app_views_layouts_base_html_erb__2684869805597434195_43205880'
  app/controllers/application_controller.rb:488:in `block (2 levels) in render_error'
  app/controllers/application_controller.rb:486:in `render_error'
  app/controllers/application_controller.rb:474:in `render_404'
  app/controllers/application_controller.rb:498:in `missing_template'
```

**Comment by peclik** [comment]
v1.9 is incompatible with 3.3, use v1.12.

**Comment by samapico** [comment]
I get the same error with v1.12 with Redmine 3.4.2
