### ISSUE TITLE
NoMethodError: undefined method `alias_method_chain' for Issue (call 'Issue.connection' to establish a connection):Class

### ISSUE THREAD

**Issue by captnjosh** [peclik/clipboard_image_paste#82]
```
C:\Bitnami\redmine-4.0.0-0\ruby\bin>ruby -v
ruby 2.3.3p222 (2016-11-21 revision 56859) [i386-mingw32]

C:\Bitnami\redmine-4.0.0-0\ruby\bin>gem --version
2.6.14

C:\Bitnami\redmine-4.0.0-0\ruby\bin>rails -v
Rails 5.2.2
```

NoMethodError: undefined method `alias_method_chain' for Issue (call 'Issue.connection' to establish a connection):Class
C:/Bitnami/redmine-4.0.0-0/apps/redmine/htdocs/vendor/bundle/ruby/2.3.0/gems/activerecord-5.2.2/lib/active_record/dynamic_matchers.rb:22:in `method_missing'
C:/Bitnami/redmine-4.0.0-0/apps/redmine/htdocs/plugins/clipboard_image_paste/lib/clipboard_image_paste/attachment_patch.rb:25:in `block in included'
C:/Bitnami/redmine-4.0.0-0/apps/redmine/htdocs/plugins/clipboard_image_paste/lib/clipboard_image_paste/attachment_patch.rb:20:in `class_eval'
C:/Bitnami/redmine-4.0.0-0/apps/redmine/htdocs/plugins/clipboard_image_paste/lib/clipboard_image_paste/attachment_patch.rb:20:in `included'
C:/Bitnami/redmine-4.0.0-0/apps/redmine/htdocs/plugins/clipboard_image_paste/lib/clipboard_image_paste/attachment_patch.rb:105:in `include'
C:/Bitnami/redmine-4.0.0-0/apps/redmine/htdocs/plugins/clipboard_image_paste/lib/clipboard_image_paste/attachment_patch.rb:105:in `<top (required)>'
C:/Bitnami/redmine-4.0.0-0/apps/redmine/htdocs/vendor/bundle/ruby/2.3.0/gems/activesupport-5.2.2/lib/active_support/dependencies.rb:291:in `require'
C:/Bitnami/redmine-4.0.0-0/apps/redmine/htdocs/vendor/bundle/ruby/2.3.0/gems/activesupport-5.2.2/lib/active_support/dependencies.rb:291:in `block in require'
C:/Bitnami/redmine-4.0.0-0/apps/redmine/htdocs/vendor/bundle/ruby/2.3.0/gems/activesupport-5.2.2/lib/active_support/dependencies.rb:257:in `load_dependency'
C:/Bitnami/redmine-4.0.0-0/apps/redmine/htdocs/vendor/bundle/ruby/2.3.0/gems/activesupport-5.2.2/lib/active_support/dependencies.rb:291:in `require'
C:/Bitnami/redmine-4.0.0-0/apps/redmine/htdocs/vendor/bundle/ruby/2.3.0/gems/activesupport-5.2.2/lib/active_support/dependencies.rb:378:in `block in require_or_load'
C:/Bitnami/redmine-4.0.0-0/apps/redmine/htdocs/vendor/bundle/ruby/2.3.0/gems/activesupport-5.2.2/lib/active_support/dependencies.rb:37:in `block in load_interlock'
C:/Bitnami/redmine-4.0.0-0/apps/redmine/htdocs/vendor/bundle/ruby/2.3.0/gems/activesupport-5.2.2/lib/active_support/dependencies/interlock.rb:14:in `block in loading'
C:/Bitnami/redmine-4.0.0-0/apps/redmine/htdocs/vendor/bundle/ruby/2.3.0/gems/activesupport-5.2.2/lib/active_support/concurrency/share_lock.rb:151:in `exclusive'
C:/Bitnami/redmine-4.0.0-0/apps/redmine/htdocs/vendor/bundle/ruby/2.3.0/gems/activesupport-5.2.2/lib/active_support/dependencies/interlock.rb:13:in `loading'
C:/Bitnami/redmine-4.0.0-0/apps/redmine/htdocs/vendor/bundle/ruby/2.3.0/gems/activesupport-5.2.2/lib/active_support/dependencies.rb:37:in `load_interlock'
C:/Bitnami/redmine-4.0.0-0/apps/redmine/htdocs/vendor/bundle/ruby/2.3.0/gems/activesupport-5.2.2/lib/active_support/dependencies.rb:356:in `require_or_load'
C:/Bitnami/redmine-4.0.0-0/apps/redmine/htdocs/vendor/bundle/ruby/2.3.0/gems/activesupport-5.2.2/lib/active_support/dependencies.rb:334:in `depend_on'
C:/Bitnami/redmine-4.0.0-0/apps/redmine/htdocs/vendor/bundle/ruby/2.3.0/gems/activesupport-5.2.2/lib/active_support/dependencies.rb:246:in `require_dependency'
C:/Bitnami/redmine-4.0.0-0/apps/redmine/htdocs/plugins/clipboard_image_paste/init.rb:35:in `block in <top (required)>'
C:/Bitnami/redmine-4.0.0-0/apps/redmine/htdocs/vendor/bundle/ruby/2.3.0/gems/activesupport-5.2.2/lib/active_support/callbacks.rb:426:in `instance_exec'
C:/Bitnami/redmine-4.0.0-0/apps/redmine/htdocs/vendor/bundle/ruby/2.3.0/gems/activesupport-5.2.2/lib/active_support/callbacks.rb:426:in `block in make_lambda'
C:/Bitnami/redmine-4.0.0-0/apps/redmine/htdocs/vendor/bundle/ruby/2.3.0/gems/activesupport-5.2.2/lib/active_support/callbacks.rb:198:in `block (2 levels) in halting'
C:/Bitnami/redmine-4.0.0-0/apps/redmine/htdocs/vendor/bundle/ruby/2.3.0/gems/activesupport-5.2.2/lib/active_support/callbacks.rb:606:in `block (2 levels) in default_terminator'
C:/Bitnami/redmine-4.0.0-0/apps/redmine/htdocs/vendor/bundle/ruby/2.3.0/gems/activesupport-5.2.2/lib/active_support/callbacks.rb:605:in `catch'
C:/Bitnami/redmine-4.0.0-0/apps/redmine/htdocs/vendor/bundle/ruby/2.3.0/gems/activesupport-5.2.2/lib/active_support/callbacks.rb:605:in `block in default_terminator'
C:/Bitnami/redmine-4.0.0-0/apps/redmine/htdocs/vendor/bundle/ruby/2.3.0/gems/activesupport-5.2.2/lib/active_support/callbacks.rb:199:in `block in halting'
C:/Bitnami/redmine-4.0.0-0/apps/redmine/htdocs/vendor/bundle/ruby/2.3.0/gems/activesupport-5.2.2/lib/active_support/callbacks.rb:513:in `block in invoke_before'
C:/Bitnami/redmine-4.0.0-0/apps/redmine/htdocs/vendor/bundle/ruby/2.3.0/gems/activesupport-5.2.2/lib/active_support/callbacks.rb:513:in `each'
C:/Bitnami/redmine-4.0.0-0/apps/redmine/htdocs/vendor/bundle/ruby/2.3.0/gems/activesupport-5.2.2/lib/active_support/callbacks.rb:513:in `invoke_before'
C:/Bitnami/redmine-4.0.0-0/apps/redmine/htdocs/vendor/bundle/ruby/2.3.0/gems/activesupport-5.2.2/lib/active_support/callbacks.rb:131:in `run_callbacks'
C:/Bitnami/redmine-4.0.0-0/apps/redmine/htdocs/vendor/bundle/ruby/2.3.0/gems/activesupport-5.2.2/lib/active_support/reloader.rb:89:in `prepare!'
C:/Bitnami/redmine-4.0.0-0/apps/redmine/htdocs/vendor/bundle/ruby/2.3.0/gems/railties-5.2.2/lib/rails/application/finisher.rb:63:in `block in <module:Finisher>'
C:/Bitnami/redmine-4.0.0-0/apps/redmine/htdocs/vendor/bundle/ruby/2.3.0/gems/railties-5.2.2/lib/rails/initializable.rb:32:in `instance_exec'
C:/Bitnami/redmine-4.0.0-0/apps/redmine/htdocs/vendor/bundle/ruby/2.3.0/gems/railties-5.2.2/lib/rails/initializable.rb:32:in `run'
C:/Bitnami/redmine-4.0.0-0/apps/redmine/htdocs/vendor/bundle/ruby/2.3.0/gems/railties-5.2.2/lib/rails/initializable.rb:61:in `block in run_initializers'
C:/Bitnami/redmine-4.0.0-0/apps/redmine/htdocs/vendor/bundle/ruby/2.3.0/gems/railties-5.2.2/lib/rails/initializable.rb:60:in `run_initializers'
C:/Bitnami/redmine-4.0.0-0/apps/redmine/htdocs/vendor/bundle/ruby/2.3.0/gems/railties-5.2.2/lib/rails/application.rb:361:in `initialize!'
C:/Bitnami/redmine-4.0.0-0/apps/redmine/htdocs/config/environment.rb:14:in `<top (required)>'
C:/Bitnami/redmine-4.0.0-0/apps/redmine/htdocs/vendor/bundle/ruby/2.3.0/gems/activesupport-5.2.2/lib/active_support/dependencies.rb:291:in `require'
C:/Bitnami/redmine-4.0.0-0/apps/redmine/htdocs/vendor/bundle/ruby/2.3.0/gems/activesupport-5.2.2/lib/active_support/dependencies.rb:291:in `block in require'
C:/Bitnami/redmine-4.0.0-0/apps/redmine/htdocs/vendor/bundle/ruby/2.3.0/gems/activesupport-5.2.2/lib/active_support/dependencies.rb:257:in `load_dependency'
C:/Bitnami/redmine-4.0.0-0/apps/redmine/htdocs/vendor/bundle/ruby/2.3.0/gems/activesupport-5.2.2/lib/active_support/dependencies.rb:291:in `require'
C:/Bitnami/redmine-4.0.0-0/apps/redmine/htdocs/vendor/bundle/ruby/2.3.0/gems/railties-5.2.2/lib/rails/application.rb:337:in `require_environment!'
C:/Bitnami/redmine-4.0.0-0/apps/redmine/htdocs/vendor/bundle/ruby/2.3.0/gems/railties-5.2.2/lib/rails/application.rb:520:in `block in run_tasks_blocks'
C:/Bitnami/redmine-4.0.0-0/apps/redmine/htdocs/vendor/bundle/ruby/2.3.0/gems/rake-12.3.2/exe/rake:27:in `<top (required)>'
Tasks: TOP => redmine:plugins:migrate => environment
(See full trace by running task with --trace)

**Comment by 87abhii** [comment]
please can somebody help i have the same issue

**Comment by ilpssun** [comment]
Duplicate of #83

**Comment by CDRO** [comment]
This is solved by #91
